"""Initial commit

Revision ID: 73fb1193f325
Revises: 
Create Date: 2026-01-16 16:02:49.508111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fb1193f325'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parserstate',
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('last_loaded_date', sa.Date(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('source')
    )
    op.create_table('spamixtradingresults',
    sa.Column('exchange_product_id', sa.String(length=24), nullable=False),
    sa.Column('exchange_product_name', sa.String(length=240), nullable=False),
    sa.Column('oil_id', sa.String(length=4), nullable=False),
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=False),
    sa.Column('delivery_basis_name', sa.String(length=120), nullable=False),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=False),
    sa.Column('volume', sa.SmallInteger(), nullable=True),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('count', sa.SmallInteger(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_on', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_product_id', 'date', name='uq_spamix_exchange_product_date'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spamixtradingresults')
    op.drop_table('parserstate')
    # ### end Alembic commands ###
