"""add Index for data field

Revision ID: 8d870194a2ca
Revises: 73fb1193f325
Create Date: 2026-01-18 15:38:49.239732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d870194a2ca'
down_revision: Union[str, Sequence[str], None] = '73fb1193f325'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'parserstate', ['id'])
    op.create_index(op.f('ix_spamixtradingresults_date'), 'spamixtradingresults', ['date'], unique=False)
    op.create_unique_constraint(None, 'spamixtradingresults', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'spamixtradingresults', type_='unique')
    op.drop_index(op.f('ix_spamixtradingresults_date'), table_name='spamixtradingresults')
    op.drop_constraint(None, 'parserstate', type_='unique')
    # ### end Alembic commands ###
