"""Initial commit

Revision ID: d1d0b694c8de
Revises:
Create Date: 2025-12-25 17:15:29.624770

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd1d0b694c8de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'spamixtradingresults',
        sa.Column('exchange_product_id', sa.String(length=24), nullable=False),
        sa.Column('exchange_product_name', sa.String(length=240), nullable=False),
        sa.Column('oil_id', sa.String(length=4), nullable=False),
        sa.Column('delivery_basis_id', sa.String(length=3), nullable=False),
        sa.Column('delivery_basis_name', sa.String(length=120), nullable=False),
        sa.Column('delivery_type_id', sa.String(length=1), nullable=False),
        sa.Column('volume', sa.SmallInteger(), nullable=True),
        sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column('count', sa.SmallInteger(), nullable=True),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column(
            'created_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column(
            'updated_on',
            sa.TIMESTAMP(timezone=True),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spamixtradingresults')
    # ### end Alembic commands ###
